services:
  postgres:
    image: "postgres:16"
    container_name: "postgres-app"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5434:5432"
    volumes:
      - ".pgdata/postgres-app:/var/lib/postgresql/data"
